

services:
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3200:3100"      # Loki exposed on 3200
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml
      - D:/loki-logging/logs:/var/log/dienluc
    command: -config.file=/etc/promtail/promtail.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3300:3000"      # Grafana exposed on 3300
