server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "dienluc"
    static_configs:
      - targets:
          - localhost
        labels:
          job: dienluc
          # Sử dụng * để gom tất cả log TP1, TP2, TP3 vào chung một cấu hình cho gọn
          __path__: /var/log/dienluc/*.log

    # THÊM PHẦN NÀY ĐỂ XỬ LÝ JSON
    pipeline_stages:
      - json:
          expressions:
            output_level: level     # Lấy field "level" trong JSON
            output_city: city       # Lấy field "city" trong JSON
            output_msg: message     # Lấy field "message"
            output_time: timestamp  # Lấy field "timestamp"

      - labels:
          level: output_level       # Biến level thành Label để filter trên Grafana
          city: output_city         # Biến city thành Label để filter

      - timestamp:
          source: output_time
          format: RFC3339           # Định dạng ngày tháng của Winston mặc định